name: my_kid
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2   # Firebase'i başlatmak için gerekli
  firebase_auth: ^4.15.3   # Firebase Authentication
  cloud_firestore: ^4.5.1
  google_sign_in: ^6.1.6
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.14.0

flutter:
  assets:
    - assets/
 
  uses-material-design: true

 