// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SILCbNPuksp8FsV_E9uUdih3VmwewpY',
    appId: '1:741740855663:web:867068714b0107bf9ea89a',
    messagingSenderId: '741740855663',
    projectId: 'mycoachapp-17bee',
    authDomain: 'mycoachapp-17bee.firebaseapp.com',
    storageBucket: 'mycoachapp-17bee.firebasestorage.app',
    measurementId: 'G-4JCE3ZSM2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVReEjD3yw4r9bIbCkB1l8DFaPsTbaZE',
    appId: '1:741740855663:android:d29d131d31170c4d9ea89a',
    messagingSenderId: '741740855663',
    projectId: 'mycoachapp-17bee',
    storageBucket: 'mycoachapp-17bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_7cG2IU2mK-zvYR7yac4PN9tmHvRWH0',
    appId: '1:741740855663:ios:164fb12bf5ae14ff9ea89a',
    messagingSenderId: '741740855663',
    projectId: 'mycoachapp-17bee',
    storageBucket: 'mycoachapp-17bee.firebasestorage.app',
    iosBundleId: 'com.example.myKid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_7cG2IU2mK-zvYR7yac4PN9tmHvRWH0',
    appId: '1:741740855663:ios:164fb12bf5ae14ff9ea89a',
    messagingSenderId: '741740855663',
    projectId: 'mycoachapp-17bee',
    storageBucket: 'mycoachapp-17bee.firebasestorage.app',
    iosBundleId: 'com.example.myKid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SILCbNPuksp8FsV_E9uUdih3VmwewpY',
    appId: '1:741740855663:web:46a92b9a43b91f0f9ea89a',
    messagingSenderId: '741740855663',
    projectId: 'mycoachapp-17bee',
    authDomain: 'mycoachapp-17bee.firebaseapp.com',
    storageBucket: 'mycoachapp-17bee.firebasestorage.app',
    measurementId: 'G-4VDFBHKYJS',
  );
}
